import type {
  Village,
  Scheme,
  Member,
  GramSabhaMeeting,
  DevelopmentWork,
  Complaint,
  Event,
  Attraction,
  Amenity,
  Announcement,
  ServiceLink,
  Alert,
  Tender,
  Asset,
} from './types';

export const mockVillages: Village[] = [
  {
    id: 1,
    name: 'Rajpur',
    slug: 'rajpur',
    taluka_id: 1,
    taluka_name: 'Dholka',
    district: 'Ahmedabad',
    state: 'Gujarat',
    latitude: 22.7196,
    longitude: 72.5797,
    default_language: 'gu',
    is_active: true,
  },
  {
    id: 2,
    name: 'Vasna',
    slug: 'vasna',
    taluka_id: 1,
    taluka_name: 'Dholka',
    district: 'Ahmedabad',
    state: 'Gujarat',
    latitude: 22.7396,
    longitude: 72.5597,
    default_language: 'gu',
    is_active: true,
  },
  {
    id: 3,
    name: 'Bavla',
    slug: 'bavla',
    taluka_id: 2,
    taluka_name: 'Bavla',
    district: 'Ahmedabad',
    state: 'Gujarat',
    latitude: 22.8296,
    longitude: 72.3697,
    default_language: 'gu',
    is_active: true,
  },
];

export const mockSchemes: Scheme[] = [
  {
    id: 1,
    code: 'PMAY-G',
    department: 'Rural Development',
    category: 'HOUSING',
    is_active: true,
    state_level: false,
    central_level: true,
    created_at: '2024-01-01',
    name: 'Pradhan Mantri Awaas Yojana - Gramin',
    short_description: 'Financial assistance for construction of pucca house to eligible rural households.',
    full_description: 'PMAY-G provides financial assistance to homeless families and those living in kutcha/dilapidated houses for construction of pucca houses with basic amenities.',
    eligibility_text: 'Houseless families or families living in houses with kutcha walls and roof. Priority to SC/ST, minorities, and disabled persons.',
    documents_required: 'Aadhaar Card, Bank Account, Land Documents, BPL Certificate, Caste Certificate (if applicable)',
  },
  {
    id: 2,
    code: 'MGNREGA',
    department: 'Rural Development',
    category: 'EMPLOYMENT',
    is_active: true,
    state_level: false,
    central_level: true,
    created_at: '2024-01-01',
    name: 'Mahatma Gandhi NREGA',
    short_description: 'Guaranteed 100 days of wage employment to rural households.',
    full_description: 'The scheme guarantees 100 days of wage employment in a financial year to every rural household whose adult members volunteer to do unskilled manual work.',
    eligibility_text: 'Any adult member of a rural household willing to do unskilled manual work at the statutory minimum wage.',
    documents_required: 'Aadhaar Card, Job Card, Bank Account',
  },
  {
    id: 3,
    code: 'NSAP-IGNOAPS',
    department: 'Social Justice',
    category: 'PENSION',
    is_active: true,
    state_level: false,
    central_level: true,
    created_at: '2024-01-01',
    name: 'Indira Gandhi National Old Age Pension',
    short_description: 'Monthly pension for elderly BPL individuals.',
    full_description: 'Provides monthly pension to eligible elderly persons belonging to Below Poverty Line (BPL) families.',
    eligibility_text: 'Age 60 years or above, belonging to BPL family.',
    documents_required: 'Aadhaar Card, Age Proof, BPL Certificate, Bank Account',
  },
  {
    id: 4,
    code: 'PM-KISAN',
    department: 'Agriculture',
    category: 'AGRICULTURE',
    is_active: true,
    state_level: false,
    central_level: true,
    created_at: '2024-01-01',
    name: 'PM Kisan Samman Nidhi',
    short_description: 'Direct income support of Rs 6000 per year to farmer families.',
    full_description: 'Income support scheme providing Rs 6000 per year in three equal installments to small and marginal farmer families.',
    eligibility_text: 'Small and marginal farmers with cultivable land holding.',
    documents_required: 'Aadhaar Card, Land Records, Bank Account',
  },
];

export const mockMembers: Member[] = [
  {
    id: 1,
    village_id: 1,
    name: 'Rameshbhai Patel',
    role: 'SARPANCH',
    ward_no: undefined,
    photo: undefined,
    phone_public: '9876543210',
    email_public: 'sarpanch.rajpur@gmail.com',
    term_start: '2022-01-01',
    term_end: '2027-01-01',
    is_active: true,
  },
  {
    id: 2,
    village_id: 1,
    name: 'Kantaben Shah',
    role: 'DEPUTY_SARPANCH',
    ward_no: undefined,
    phone_public: '9876543211',
    term_start: '2022-01-01',
    term_end: '2027-01-01',
    is_active: true,
  },
  {
    id: 3,
    village_id: 1,
    name: 'Maheshbhai Desai',
    role: 'SECRETARY',
    ward_no: undefined,
    phone_public: '9876543212',
    term_start: '2020-06-01',
    term_end: '2025-06-01',
    is_active: true,
  },
  {
    id: 4,
    village_id: 1,
    name: 'Sureshbhai Vaghela',
    role: 'MEMBER',
    ward_no: 1,
    phone_public: '9876543213',
    term_start: '2022-01-01',
    term_end: '2027-01-01',
    is_active: true,
  },
  {
    id: 5,
    village_id: 1,
    name: 'Jayaben Parmar',
    role: 'MEMBER',
    ward_no: 2,
    phone_public: '9876543214',
    term_start: '2022-01-01',
    term_end: '2027-01-01',
    is_active: true,
  },
];

export const mockGramSabhaMeetings: GramSabhaMeeting[] = [
  {
    id: 1,
    village_id: 1,
    title: 'Annual Gram Sabha Meeting - Q4 2024',
    date: '2025-01-15',
    start_time: '10:00',
    end_time: '13:00',
    venue: 'Village Community Hall',
    status: 'SCHEDULED',
    agenda: '1. Review of development works\n2. Budget discussion for 2025-26\n3. New scheme implementations\n4. Public grievances',
    created_by_id: 1,
  },
  {
    id: 2,
    village_id: 1,
    title: 'Special Gram Sabha - Road Development',
    date: '2024-12-01',
    start_time: '11:00',
    end_time: '14:00',
    venue: 'Village Community Hall',
    status: 'COMPLETED',
    agenda: '1. Discussion on main road expansion\n2. Contractor selection\n3. Timeline finalization',
    minutes_document: '/documents/gramsabha_dec2024.pdf',
    created_by_id: 1,
  },
];

export const mockDevelopmentWorks: DevelopmentWork[] = [
  {
    id: 1,
    village_id: 1,
    title: 'Main Village Road Expansion',
    description: 'Widening and asphalting of main village road from entrance to temple area.',
    work_type: 'ROAD',
    funding_scheme_name: 'PMGSY',
    estimated_cost: 2500000,
    approved_budget: 2500000,
    status: 'IN_PROGRESS',
    progress_percentage: 65,
    start_date: '2024-08-01',
    end_date: '2025-03-31',
  },
  {
    id: 2,
    village_id: 1,
    title: 'Community Water Tank Construction',
    description: 'Construction of 50,000 liter capacity water storage tank for drinking water supply.',
    work_type: 'WATER',
    funding_scheme_name: 'Jal Jeevan Mission',
    estimated_cost: 800000,
    approved_budget: 800000,
    status: 'APPROVED',
    progress_percentage: 0,
    start_date: '2025-02-01',
    end_date: '2025-06-30',
  },
  {
    id: 3,
    village_id: 1,
    title: 'Street Light Installation - Phase 2',
    description: 'Installation of 25 solar street lights in residential areas.',
    work_type: 'ELECTRIC',
    estimated_cost: 375000,
    approved_budget: 375000,
    status: 'COMPLETED',
    progress_percentage: 100,
    start_date: '2024-04-01',
    end_date: '2024-09-30',
  },
];

export const mockComplaints: Complaint[] = [
  {
    id: 1,
    reference_id: 'GRV-2024-000123',
    village_id: 1,
    name: 'Prakashbhai Mehta',
    phone: '9876543220',
    category: 'WATER',
    title: 'Water Supply Irregular',
    description: 'Water supply is irregular in Ward 3 since past 2 weeks. Getting water only once in 3 days.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    created_at: '2024-12-01T10:30:00Z',
    updated_at: '2024-12-05T14:20:00Z',
    assigned_to_name: 'Water Department',
  },
  {
    id: 2,
    reference_id: 'GRV-2024-000124',
    village_id: 1,
    name: 'Gitaben Solanki',
    phone: '9876543221',
    category: 'ROAD',
    title: 'Potholes on School Road',
    description: 'Multiple large potholes on the road leading to primary school. Children face difficulty going to school.',
    status: 'NEW',
    priority: 'MEDIUM',
    created_at: '2024-12-08T09:15:00Z',
    updated_at: '2024-12-08T09:15:00Z',
  },
  {
    id: 3,
    reference_id: 'GRV-2024-000120',
    village_id: 1,
    name: 'Anonymous',
    phone: '9876543222',
    category: 'ELECTRICITY',
    title: 'Street Light Not Working',
    description: 'Street light near bus stand not working for past month.',
    status: 'RESOLVED',
    priority: 'LOW',
    created_at: '2024-11-15T16:45:00Z',
    updated_at: '2024-11-25T11:30:00Z',
    assigned_to_name: 'Electricity Department',
  },
];

export const mockEvents: Event[] = [
  {
    id: 1,
    village_id: 1,
    title: 'Republic Day Celebration 2025',
    description: 'Annual Republic Day celebration with flag hoisting and cultural programs.',
    event_date: '2025-01-26',
    event_type: 'GOVT_PROGRAM',
  },
  {
    id: 2,
    village_id: 1,
    title: 'Navratri Festival 2024',
    description: 'Nine nights of Garba and cultural celebrations.',
    event_date: '2024-10-03',
    event_type: 'FESTIVAL',
  },
  {
    id: 3,
    village_id: 1,
    title: 'MLA Visit - Development Review',
    description: 'Local MLA visited to review ongoing development projects.',
    event_date: '2024-11-20',
    event_type: 'CELEBRITY_VISIT',
  },
];

export const mockAttractions: Attraction[] = [
  {
    id: 1,
    village_id: 1,
    name: 'Shree Ram Mandir',
    description: 'Ancient temple with beautiful architecture, built over 200 years ago.',
    type: 'RELIGIOUS',
    lat: 22.7196,
    lng: 72.5797,
    is_nearby: false,
  },
  {
    id: 2,
    village_id: 1,
    name: 'Village Lake',
    description: 'Scenic lake surrounded by trees, popular for evening walks.',
    type: 'NATURE',
    lat: 22.7210,
    lng: 72.5810,
    is_nearby: false,
  },
  {
    id: 3,
    village_id: 1,
    name: 'Lothal Archaeological Site',
    description: 'Ancient Indus Valley Civilization site, UNESCO heritage.',
    type: 'HISTORICAL',
    lat: 22.5226,
    lng: 72.2496,
    distance_km: 35,
    is_nearby: true,
  },
];

export const mockAmenities: Amenity[] = [
  {
    id: 1,
    village_id: 1,
    name: 'State Bank of India',
    type: 'BANK',
    address: 'Main Road, Rajpur',
    contact_phone: '079-12345678',
    opening_hours: 'Mon-Sat: 10:00 AM - 4:00 PM',
  },
  {
    id: 2,
    village_id: 1,
    name: 'Primary Health Center',
    type: 'CLINIC',
    address: 'Near Bus Stand, Rajpur',
    contact_phone: '079-12345679',
    contact_person: 'Dr. Sharma',
    opening_hours: '24x7 Emergency, OPD: 9 AM - 5 PM',
  },
  {
    id: 3,
    village_id: 1,
    name: 'Government Primary School',
    type: 'EDUCATION',
    address: 'School Road, Rajpur',
    contact_phone: '079-12345680',
    opening_hours: 'Mon-Sat: 10:30 AM - 5:00 PM',
  },
  {
    id: 4,
    village_id: 1,
    name: 'Weekly Market',
    type: 'MARKET',
    address: 'Market Chowk, Rajpur',
    opening_hours: 'Every Sunday: 7:00 AM - 1:00 PM',
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 1,
    village_id: 1,
    type: 'EMERGENCY',
    start_date: '2024-12-09',
    end_date: '2024-12-15',
    is_active: true,
    created_at: '2024-12-09T08:00:00Z',
    title: 'Water Supply Disruption Notice',
    description: 'Due to pipeline repair work, water supply will be disrupted on Dec 10-11. Please store water accordingly.',
  },
  {
    id: 2,
    village_id: 1,
    type: 'MEETING',
    start_date: '2024-12-15',
    is_active: true,
    created_at: '2024-12-05T10:00:00Z',
    title: 'Gram Sabha Meeting - January 2025',
    description: 'Annual Gram Sabha meeting scheduled for January 15, 2025 at 10:00 AM in Community Hall. All villagers are requested to attend.',
  },
  {
    id: 3,
    village_id: 1,
    type: 'NOTICE',
    start_date: '2024-12-01',
    is_active: true,
    created_at: '2024-12-01T09:00:00Z',
    title: 'PM-KISAN Registration Drive',
    description: 'Special registration camp for PM-KISAN scheme on Dec 20. Bring Aadhaar, land documents, and bank passbook.',
  },
];

export const mockServiceLinks: ServiceLink[] = [
  {
    id: 1,
    title: 'Birth Certificate',
    category: 'BIRTH_CERTIFICATE',
    description: 'Apply for birth certificate online',
    url: 'https://crsorgi.gov.in/',
    is_active: true,
  },
  {
    id: 2,
    title: 'Voter ID Services',
    category: 'VOTER',
    description: 'Apply for new voter ID or address change',
    url: 'https://voters.eci.gov.in/',
    is_active: true,
  },
  {
    id: 3,
    title: 'Land Records (AnyRoR)',
    category: 'LAND_RECORD',
    description: 'Check land records and ownership details',
    url: 'https://anyror.gujarat.gov.in/',
    is_active: true,
  },
  {
    id: 4,
    title: 'IRCTC Train Booking',
    category: 'BUS_TRAIN',
    description: 'Book train tickets online',
    url: 'https://www.irctc.co.in/',
    is_active: true,
  },
  {
    id: 5,
    title: 'Employment Exchange Registration',
    category: 'JOBS',
    description: 'Register for government job notifications',
    url: 'https://employment.gujarat.gov.in/',
    is_active: true,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 1,
    village_id: 1,
    type: 'WEATHER',
    title: 'Heavy Rain Expected',
    message: 'Heavy rainfall expected in the region for next 2 days. Take necessary precautions.',
    severity: 'WARNING',
    start_time: '2024-12-09T06:00:00Z',
    end_time: '2024-12-11T18:00:00Z',
    created_at: '2024-12-09T05:00:00Z',
  },
];

export const mockTenders: Tender[] = [
  {
    id: 1,
    village_id: 1,
    title: 'Construction of Community Hall Extension',
    description: 'Construction work for extending the existing community hall with additional 200 sq meter area.',
    work_type: 'BUILDING',
    estimated_cost: 1500000,
    status: 'OPEN',
    publish_date: '2024-12-01',
    last_date: '2024-12-31',
    external_submission_url: 'https://eprocure.gov.in/',
  },
  {
    id: 2,
    village_id: 1,
    title: 'Annual Road Maintenance Contract',
    description: 'Maintenance and repair of all village roads for financial year 2025-26.',
    work_type: 'ROAD',
    estimated_cost: 500000,
    status: 'OPEN',
    publish_date: '2024-12-05',
    last_date: '2025-01-15',
  },
];

export const mockAssets: Asset[] = [
  {
    id: 1,
    village_id: 1,
    name: 'Community Hall',
    asset_type: 'HALL',
    location_description: 'Near main chowk',
    condition_status: 'GOOD',
    installation_date: '2015-03-15',
  },
  {
    id: 2,
    village_id: 1,
    name: 'Tube Well - Ward 1',
    asset_type: 'BOREWELL',
    location_description: 'Ward 1, near temple',
    condition_status: 'GOOD',
    installation_date: '2020-06-20',
  },
  {
    id: 3,
    village_id: 1,
    name: 'Water Pipeline Network',
    asset_type: 'PIPELINE',
    location_description: 'Throughout village',
    condition_status: 'NEEDS_REPAIR',
    installation_date: '2010-01-01',
  },
  {
    id: 4,
    village_id: 1,
    name: 'Solar Street Lights (25 units)',
    asset_type: 'LIGHT',
    location_description: 'Main roads and residential areas',
    condition_status: 'GOOD',
    installation_date: '2024-09-30',
  },
  {
    id: 5,
    village_id: 1,
    name: 'Village Pond',
    asset_type: 'POND',
    location_description: 'South side of village',
    condition_status: 'NEEDS_REPAIR',
  },
];
